# Site settings
title: UW CSE 583 - Software Engineering for Data Scientists
description: "UW course, Software Engineering for Data Scientists"
url: "http://uwseds.github.io"
twitter_username: uwescience
github_username:  UWSEDS


# Build settings
markdown: kramdown
