# Site settings
title: Software Design for Data Scientists (DATA 515)
description: "Course at the University of Washington, Software Design for Data Scientists"
url: "http://uwdata515.github.io"
github_username:  UWDATA515


# Build settings
markdown: kramdown
