# Site settings
title: Software Development for Data Scientists (CSE 583)
description: "Course at the University of Washington, Software Development for Data Scientists"
url: "http://uwseds.github.io"
twitter_username: uwescience
github_username:  UWSEDS


# Build settings
markdown: kramdown
